spring:
  batch:
    job:
      enabled: false
  data:
    mongodb:
      database: super_deduper

logging:
   level:
     org.superdeduper.superdeduper: DEBUG

app:
  name: Super De-duper
  destination: c:\\temp\${app.name}\\destination
  temp: c:\\temp\\${app.name}\\temp